### ISSUE TITLE
ORF ON

### ISSUE THREAD

**Issue by killerbees19** [s0faking/plugin.video.orftvthek#134]
There're [confirmed rumors](https://www.derstandard.at/story/3000000201439/mit-dem-orf-beitrag-ist-zu-neujahr-streamingplattform-orf-on-gestartet) that "ORF ON" is the replacement for ORF TVthek.

* Current status: Public Beta
* Website: https://on.orf.at/
* Timeframe: April 2024

Are there any plans to support ORF ON (in this app or a new one), if technically feasible?

**Comment by s0faking** [comment]
yes, I'm pretty sure that ORF On will replace the Tvthek. I'm already on it, looks like that backend is pretty much the same, the ORF On Frontend is written with Nuxt and is using the ServiceAPI Endpoints. There have been a few changes on the API but nothing major. I will take this opportunity to rewrite the whole addon since the current version has been in development for over 10 years now i guess it's time to start with a clean slate and finally put the htmlscraper to a rest :)

**Comment by s0faking** [comment]
https://github.com/s0faking/plugin.video.orfon

still quite some stuff todo but basic things should already work :)

**Comment by 1Luc1** [comment]
@s0faking tvthek will be closed on 22/5/2024.
[Source](https://www.derstandard.at/story/3000000220844/orf-dreht-tvthek-endgueltig-ab). So I guess this addon won't work anymore?

**Comment by s0faking** [comment]
well kind of. the service api is still working, even with the older api version. the web scraper is broken for sure. so for now i guess switching to the service api option in the settings is the quickest way (you have to use the current master from github though because of #137), or you can use the orfon addon.

i will probably merge the orf on addon to this repo, since the old addon is pretty much deprecated now.

**Comment by 1Luc1** [comment]
@s0faking so the repo https://github.com/s0faking/plugin.video.orfon got already merged into this one? If so, its good to go to use this repo with the [latest release](https://github.com/s0faking/plugin.video.orftvthek/releases/latest)?

**Comment by s0faking** [comment]
Yes. The current version is also available in the official kodi repo
