### ISSUE TITLE
Recording/Download for onDemand or Livestreams

### ISSUE THREAD

**Issue by benjaminaigner** [s0faking/plugin.video.orftvthek#23]
Hi,

do you think that it would be possible to record a livestream?
Or download the 7days on demand?

I've never developed anything for Kodi, but if you can tell me where to start, I will make a PR.

Best regards

**Comment by s0faking** [comment]
Hi Benjamin,

i'm not sure. it used to be possible because they had an RTMP stream. RTMP streams can be dumped with rtmpdump. Now there are using HLS for the stream delivery. Might be quite hard to implement something like that into Kodi. HLS works with multiple TS Files which are delivered trough a playlist. In order to get the whole livestream the playlist has to be refetched when the loaded TS Files played to the end. After the live Stream has ended you should have a collection of TS Files. Those need to be edited in order to get an MP4 or Matroska file. 
Check out https://github.com/s0faking/playground/tree/master/hls_rip 
you might find a few things that will help you understand hls delivery / conversion

cheers,
s0fa

**Comment by mablae** [comment]
Hey, 

I think recording HLS is far out of scope of Kodi.

There are builtin recording capabilities - but only for the PVR module which acts as a client for several different PVR Service providers like TvHeadend, MythTV etc. 

Maybe it would be possible to build a "virtual" PVR Service + Kodi Client which acts as a proxy for Kodi. 
This proxy would then transcode the HLS into an MPEG Transport Stream that could be recorded to disk in Kodi. 

But it would require C++ Coding and is not worth the efforts at all I guess.

**Comment by benjaminaigner** [comment]
Hi,

thank you for the feedback, although its not working :-)

Maybe it would be possible to use some wrapper around the "MediathekView", which allows the usage/download of many public TV stations, but this is not related to your plugin.

Thank you, your plugin is nice anyway!
