### ISSUE TITLE
video downloads 0 byte size

### ISSUE THREAD

**Issue by Caballingus** [s0faking/plugin.video.orftvthek#71]
Hi s0faking
long time satisfied user here- many thanks for this great addon- 
downloading videos used to work great in previous versions.
since the last change(s) dreamcatcher/super favorites/youtube-dl 
will only detect 0 (zero) byte mp4's and hence quit or produce error messages instead of downloads.

though when activating serviceapi option, filesize shows up correct and downloads work as usual.

any ideas?
btw my Kodi version is 17.6
many thanks in advance

**Comment by s0faking** [comment]
Hi @Caballingus,
with 0.8.5 the addon doesn't use the progressive stream method anymore. hls streams are used because they are more stable, and the adaptive stream quality and uhd streams are only working with the hls method. you can fix that by changing 'videoDelivery = "hls"' to 'videoDelivery = "progressive"' in default.py.

**Comment by s0faking** [comment]
i will add a settings option for this on the next release

**Comment by Caballingus** [comment]
thanks for the quick response-

unfortunately changing the videoDelivery setting to progressive in default.py didn't quite solve the problem. instead of zero-sized files I now keep getting error messages like this when attempting a download with super favorites:
_Download failed hostname 'apasfpd.apa.at' doesn't match '*.sf.apa.at'._

**Comment by s0faking** [comment]
Hi @Caballingus,
check commit 030123c4c02ffe789b99844997fbb3e31a1e0c14. this is caused by a bad certificate issued by orf.

**Comment by s0faking** [comment]
the latest commits adds a stream type option in the settings form. if you select progressive you should be good. adaptive stream quality wont work with that setting

**Comment by killerbees19** [comment]
@s0faking Is this feature already finished and tested? Because it's impossible to change the value of `Stream Method`. It's always locked at `Programme`. Don't ask me where this string is taken from… 🤔

[Screenshot](http://666kb.com/i/dwql773slwmevbgn4.png) from Kodi 15.2 (Xubuntu 16.04) on a clean test account. (_I know, I should upgrade!_)

**Comment by s0faking** [comment]
@killerbees19 check the latest commit. apparently kodi 15 can't handle the strings in the settings.xml.

**Comment by killerbees19** [comment]
Thanks! 🙂
