### ISSUE TITLE
[Restart] and "Play Chapter" broken in most current 0.10

### ISSUE THREAD

**Issue by AloisKlingler** [s0faking/plugin.video.orftvthek#93]
Hi sofaking,

just to let you know: in the most recent master (I guess 0.10 labeled?) the "Restart" of a live stream only prints an error.
the new "Play Chapter" function results in a sad smiley (I use OSMC with kodi 18.5), the new "Play all" function most time does not appear in my folders.

I am back to 0.9.1 currently. :-)

Best regards

**Comment by s0faking** [comment]
hi alois,

thx, i already fixed the restart error with a396fbb

looking into the "play chapter" problem now. this problem seems to be linux specific because it doesnt occur on windows. had the problem on my rpis and on my shield though. 

the "play all" function isn't showing because its probably disabled by orf. i think there might be  a problem with the streaming services because the gapless feature wasn't working very well a week ago(stream jumps and stuff like that). when they turn in back on the "play all" item will appear automatically

**Comment by s0faking** [comment]
5e26ae4 should fix the "play chapter" crashes. can you test this on your osmc?

**Comment by AloisKlingler** [comment]
Hi,
Yes I can, will do today evening and report back. 

Best regards

**Comment by AloisKlingler** [comment]
Both are fixed on osmc  with current master. Thank you!

**Comment by s0faking** [comment]
is service api enabled? 0.12.3 is the most recent version. this version fixes issues with restart when using the service api.

**Comment by UserX404** [comment]
0.12.3 isn't available. I manually downloaded the version from git but i'm not able to install. Not sure if i remember corect but maybe no python 3 dependency availabe.
Service api is not enabled. Is it necessary for the restart feature?

**Comment by UserX404** [comment]
Thanks. Live is working again but Restart does nothing.
Kodu.log on klicking Restart:
```
2021-10-18 22:30:57.712 T:2472444736 WARNING: Previous line repeats 3 times.
2021-10-18 22:30:57.712 T:2472444736  NOTICE: [script.module.inputstreamhelper] Widevine update check was made on 2021-09-22 21:52
```
